### PR TITLE
Python 3.14 compatibility (_ctypes)

### PR DESCRIPTION
**Pull request by porly1985**
Import pointer from ctypes instead of _ctypes. 

Using Python 3.14 import pointer from _ctypes causes the following exception:

`ImportError: cannot import name 'pointer' from '_ctypes' (C:\Users\paulk\AppData\Local\Programs\Python\Python314\DLLs\_ctypes.pyd)`

Seems that there have been some changes in 3.14. Changing _ctypes to ctypes fixed the issue for me and is working on Python 3.13 and 3.14. Hard to say for me if it has impact on earlier Python versions.

### CODE REVIEW

**Comment by porly1985** [comment]
Added conditional import to ensure backwards compatibility.

**Review by cmbruns — APPROVED** [review]
